### ISSUE TITLE
Not in Maven Central

### ISSUE THREAD

**Issue by leonjones1974** [orolle/SMC#1] opened 2015-07-16 11:41 UTC
There's a couple of nice things in this fork that make it more suited to my project than the original.  I cannot find any artifacts in maven central though (despite the pom containing all the publishing info).

Is there a reason it's not there or am I just missing it?

Thanks,
Leon

**Comment by orolle** [comment] 2015-07-23 17:06
it should be in central. I pushed it via sonatype oss. See: https://maven-repository.com/search?q=com.github.orolle
Can you verify if the problem is on my / your side? So that I can escalate or close the issue.

**Comment by leonjones1974** [comment] 2015-07-23 17:27
Thanks - I'm just about to go away for 10 days - I'll get on it when I get back if you don't mind keeping the issue open.

Cheers
Leon

**Comment by leonjones1974** [comment] 2015-07-23 19:10
Just had a look and it is where you say it is, but not where I'd normally find artifacts, which would be here: http://search.maven.org/#search%7Cga%7C1%7Corelle

My own artifacts are sync'd to both, but seems yours are not for some reason.

It's not a big deal, I can add the other repo to my chain, but I'd be interested to know which is the 'real' maven central

**Comment by orolle** [comment] 2015-08-13 16:52
I looked into this issue, but I have no idea and I am an absolute novice on maven artifact distribution. I distributed the my artifacts via oss.sonatype.org (http://central.sonatype.org/pages/ossrh-guide.html). How do you distribute your artifacts?

**Comment by leonjones1974** [comment] 2015-08-14 13:41
Exactly the same way :( Perhaps you were just unlucky and the sync failed for that particular publish?

**Comment by ericrycuny** [comment] 2017-02-12 10:21
Hi,
I think this fork is very interesting, the new rx add-on  makes me want to dig deeper, unfortunately when I add the dependency I get the following 
`[WARNING] The POM for com.github.orolle:smc-lib-java:jar:6.4.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
`
is there a way to make it work ?

thanks

**Comment by orolle** [comment] 2017-02-12 12:10
Hi, 
thanks for your interest! 
I pushed my latest code and triggered a release to maven central. Should be available latest tomorrow. Can you verify that for me? 
The artifacts seems to be available: http://search.maven.org/#search%7Cga%7C1%7Ccom.github.orolle
Releasing a OSS software via sonatype to maven central is a pain in the a** - complex and error prone process. I hope I did it right this time.

**Comment by leonjones1974** [comment] 2017-02-12 12:45
Looks like the original author is helping you out.  Let me know if you have problems and I can have a go at updating my fork to include the new rx module.
If you are doing rx'y stuff, you might want to check-out my test dsl

https://github.com/leonjones1974/rx
<cleaned up email response>

**Comment by ericrycuny** [comment] 2017-02-12 14:57
@orolle
Great I had success using this :)
`   <dependencies>
        <dependency>
            <groupId>com.github.orolle</groupId>
            <artifactId>smc-lib-java</artifactId>
            <version>6.4.0_rx_b1</version>
        </dependency>
    </dependencies>
`
And intelliJ succeeded building with maven 3.3.9.

here is the working project 

https://github.com/ericrycuny/MyTurnstile

@leonjones1974 
Nice to be in touch with you as well ! Once I'll figure out how to use SMCrx then I'll also soon give a try at your 
https://github.com/leonjones1974/rx

@both : By the way I'm really impressed how fast you replied guys, well done !

Thanks

**Comment by orolle** [comment] 2017-02-13 12:27
You are welcome! If you have questions, feel free to contact me.
I close this issue now.

**Closed as completed by orolle** 2017-02-13 12:27 UTC

**Comment by orolle** [comment] 2017-02-13 18:38
@leonjones1974 @ericrycuny You guys seem to be interested in rx, I have another rx project. The project contains a wrapper (DistributedObservable) to translate between Observable and vertx (distributed) event bus. It enables to write rx-ified vertx apps easily. https://github.com/orolle/micro-service-rx/tree/master/core/src/main/java/microservicerx/rx
Also this demo project rx-ifies vertx micro services to enable push-based micro services (kind of like components in flow based programming). Use it in conjunction with _interacting_ SMC state machines to represent business logic as a service.

**Comment by ericrycuny** [comment] 2017-02-13 19:11
thanks I'll have to learn a thing or two about vert.x firsthand, do you think it s a good start 
http://vertx.io/blog/my-first-vert-x-3-application/
?

**Comment by orolle** [comment] 2017-02-13 19:34
yes try it out. if you need a library for distributed computing or io /
networking intensive tasks it's a good choice.

Am 13.02.2017 20:12 schrieb "ericrycuny" <notifications@github.com>:
